import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // `next-env.d.ts` is auto-generated by `next build` / `next dev` and
    // per Next.js docs "should not be edited". Next 15.5.20 added a third
    // triple-slash reference (`/// <reference path="./.next/types/routes.d.ts" />`)
    // which trips @typescript-eslint/triple-slash-reference in `next/typescript`.
    // Ignoring the whole file matches Next's own guidance.
    ignores: ["node_modules/**", ".next/**", "convex/_generated/**", "out/**", "next-env.d.ts"],
  },
  {
    rules: {
      // priority_tier is server-owned; surface any accidental client write
      // of forbidden fields during review rather than relying on lint alone.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
